import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1A1A1A',
    backgroundColor: 'rgba(0,0,0,0.9)',
  },
  logoBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(212,245,60,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(212,245,60,0.3)',
  },
  logoText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 20,
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  logoTagline: {
    fontFamily: 'Inter_500Medium',
    fontSize: 9,
    color: '#D4F53C',
    letterSpacing: 2,
  },
  navLinks: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusLive: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#222',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  statusText: {
    color: '#AAA',
    fontSize: 12,
  },
  loginBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#D4F53C',
    borderRadius: 100,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  loginBtnText: {
    fontFamily: 'Inter_700Bold',
    color: '#000000',
    fontSize: 14,
  },
  heroSection: {
    alignItems: 'center',
    marginTop: 60,
    marginBottom: 80,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: 'rgba(204, 255, 0, 0.1)',
    borderRadius: 100,
    borderWidth: 1,
    borderColor: 'rgba(204, 255, 0, 0.3)',
    marginBottom: 24,
  },
  badgeText: {
    color: '#D4F53C',
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    letterSpacing: 1.5,
  },
  heroTitle: {
    fontFamily: 'Inter_700Bold',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: -1,
    marginBottom: 24,
  },
  heroSubtitle: {
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    color: '#A1A1AA',
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 36,
  },
  ctaContainer: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 60,
  },
  primaryCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#D4F53C',
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
  },
  primaryCtaText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    color: '#000000',
  },
  statsRow: {
    backgroundColor: '#0E0E10',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#222',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: 20,
  },
  statBox: {
    alignItems: 'center',
  },
  statNumber: {
    color: '#D4F53C',
    fontSize: 28,
    fontFamily: 'Inter_700Bold',
  },
  statLabel: {
    color: '#888',
    fontSize: 12,
    marginTop: 4,
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#222',
  },
  sectionContainer: {
    marginBottom: 100,
  },
  sectionHeader: {
    alignItems: 'center',
    marginBottom: 40,
  },
  miniTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(212,245,60,0.08)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(212,245,60,0.2)',
    marginBottom: 12,
  },
  miniTagText: {
    color: '#D4F53C',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    letterSpacing: 1,
  },
  sectionHeading: {
    fontFamily: 'Inter_700Bold',
    fontSize: 32,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 12,
  },
  sectionSub: {
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    color: '#888',
    textAlign: 'center',
    maxWidth: 640,
    lineHeight: 22,
  },
  mockupTabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#16161A',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  mockupTabBtnActive: {
    backgroundColor: '#D4F53C',
    borderColor: '#D4F53C',
  },
  mockupTabBtnText: {
    color: '#888',
    fontSize: 13,
  },
  mockupDisplayCard: {
    backgroundColor: '#0F0F12',
    borderRadius: 24,
    padding: 28,
    borderWidth: 1,
    borderColor: '#222',
  },
  loggerSetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#16161A',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    gap: 12,
  },
  checkPill: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#D4F53C',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heatmapMetricBox: {
    flex: 1,
    backgroundColor: '#16161A',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  aiChatBubbleBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: 'rgba(212,245,60,0.06)',
    padding: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(212,245,60,0.2)',
  },
  toolCard: {
    backgroundColor: '#0F0F12',
    borderRadius: 24,
    padding: 32,
    borderWidth: 1,
    borderColor: '#222',
  },
  inputLabel: {
    color: '#888',
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    letterSpacing: 1,
    marginBottom: 8,
  },
  textInputStyle: {
    backgroundColor: '#16161A',
    color: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  oneRmResultBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#16161A',
    padding: 24,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#333',
    flexWrap: 'wrap',
    gap: 16,
  },
  strengthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(212,245,60,0.1)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(212,245,60,0.3)',
  },
  pctBox: {
    backgroundColor: '#16161A',
    borderRadius: 12,
    padding: 14,
    flex: 1,
    minWidth: 120,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  barbellVisualArea: {
    backgroundColor: '#141418',
    borderRadius: 18,
    padding: 24,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  barbellCenterBar: {
    width: 90,
    height: 18,
    backgroundColor: '#888',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  plateGraphic: {
    width: 22,
    height: 70,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#000',
  },
  plateGraphicText: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#FFF',
    transform: [{ rotate: '-90deg' }],
  },
  barbellCollar: {
    width: 14,
    height: 36,
    backgroundColor: '#444',
    borderRadius: 4,
  },
  goalBtn: {
    flex: 1,
    backgroundColor: '#16161A',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    alignItems: 'center',
  },
  goalBtnActive: {
    backgroundColor: '#D4F53C',
    borderColor: '#D4F53C',
  },
  goalBtnText: {
    color: '#888',
    fontSize: 12,
    textAlign: 'center',
  },
  macroItemLarge: {
    flex: 1,
    backgroundColor: '#16161A',
    borderRadius: 16,
    padding: 18,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  splitDayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#16161A',
    padding: 16,
    borderRadius: 14,
    gap: 16,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  splitDayBadge: {
    backgroundColor: 'rgba(212,245,60,0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  hrZoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#16161A',
    padding: 16,
    borderRadius: 14,
    gap: 16,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  hrZoneTitle: {
    fontSize: 12,
    fontFamily: 'Inter_700Bold',
  },
  simulatorWrapper: {
    backgroundColor: '#0F0F12',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#222',
    overflow: 'hidden',
    gap: 24,
    padding: 24,
  },
  simSelector: {
    gap: 10,
  },
  simTab: {
    backgroundColor: '#16161A',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  simTabActive: {
    backgroundColor: 'rgba(212,245,60,0.06)',
    borderColor: '#D4F53C',
  },
  simTabTitle: {
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'Inter_700Bold',
  },
  simTabPercent: {
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
  },
  simProgressBarBg: {
    height: 6,
    backgroundColor: '#222',
    borderRadius: 3,
    marginTop: 10,
    overflow: 'hidden',
  },
  simProgressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  simDisplay: {
    justifyContent: 'center',
  },
  telemetryCard: {
    backgroundColor: '#18181C',
    borderRadius: 18,
    padding: 24,
    borderWidth: 1,
    borderColor: '#333',
  },
  telemetryTitle: {
    color: '#FFF',
    fontSize: 20,
    fontFamily: 'Inter_700Bold',
  },
  telemetrySubtitle: {
    color: '#888',
    fontSize: 12,
    marginTop: 4,
  },
  fatigueBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  fatigueBadgeText: {
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
  },
  telemetryMetricsRow: {
    flexDirection: 'row',
    gap: 12,
    marginVertical: 18,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#101014',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  metricLabel: {
    color: '#888',
    fontSize: 10,
    letterSpacing: 0.5,
  },
  metricVal: {
    color: '#FFF',
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    marginTop: 4,
  },
  exerciseBox: {
    backgroundColor: '#121216',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  exerciseBoxTitle: {
    color: '#888',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    letterSpacing: 0.5,
  },
  exTag: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  exTagText: {
    color: '#DDD',
    fontSize: 11,
  },
  aiAdviceBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(212,245,60,0.06)',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(212,245,60,0.2)',
  },
  aiAdviceText: {
    color: '#D4F53C',
    fontSize: 12,
    flex: 1,
  },
  modeToggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#16161A',
    borderRadius: 100,
    padding: 6,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    marginTop: 24,
  },
  modeToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 100,
  },
  modeToggleBtnActive: {
    backgroundColor: '#D4F53C',
  },
  modeToggleText: {
    color: '#888',
    fontSize: 13,
  },
  modeShowcaseCard: {
    backgroundColor: '#121216',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#222',
    overflow: 'hidden',
  },
  modeCardBadge: {
    color: '#D4F53C',
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  modeCardTitle: {
    color: '#FFF',
    fontSize: 24,
    fontFamily: 'Inter_700Bold',
    marginBottom: 12,
  },
  modeCardDesc: {
    color: '#888',
    fontSize: 14,
    lineHeight: 22,
  },
  modeMockBox: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#18181C',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#333',
  },
  mockRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#222',
  },
  foodChip: {
    backgroundColor: '#16161A',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  foodChipActive: {
    backgroundColor: '#D4F53C',
    borderColor: '#D4F53C',
  },
  foodChipText: {
    color: '#888',
    fontSize: 13,
  },
  foodCard: {
    backgroundColor: '#101014',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  macroItem: {
    flex: 1,
    backgroundColor: '#18181C',
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 3,
  },
  volumeCalcBox: {
    backgroundColor: '#101014',
    borderRadius: 24,
    padding: 28,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  volPresetBtn: {
    backgroundColor: '#18181C',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  volPresetBtnActive: {
    backgroundColor: '#D4F53C',
    borderColor: '#D4F53C',
  },
  volPresetText: {
    color: '#888',
    fontSize: 13,
  },
  volResultCard: {
    backgroundColor: '#18181C',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },
  pricingRow: {
    gap: 24,
  },
  pricingCard: {
    backgroundColor: '#101014',
    borderRadius: 24,
    padding: 32,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    position: 'relative',
  },
  pricingCardPro: {
    borderColor: '#D4F53C',
    backgroundColor: 'rgba(212,245,60,0.03)',
  },
  popularBadge: {
    position: 'absolute',
    top: -12,
    right: 24,
    backgroundColor: '#D4F53C',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  planName: {
    color: '#888',
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
    letterSpacing: 1.5,
  },
  planPrice: {
    color: '#FFF',
    fontSize: 34,
    fontFamily: 'Inter_700Bold',
    marginVertical: 10,
  },
  planPeriod: {
    color: '#888',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
  },
  planDesc: {
    color: '#888',
    fontSize: 13,
    lineHeight: 18,
  },
  planBtnSecondary: {
    backgroundColor: '#222',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  planBtnPrimary: {
    backgroundColor: '#D4F53C',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  faqCard: {
    backgroundColor: '#101014',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  faqQ: {
    color: '#FFF',
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
    flex: 1,
    paddingRight: 12,
  },
  faqA: {
    color: '#888',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#222',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 32,
    borderTopWidth: 1,
    borderTopColor: '#1A1A1A',
    flexWrap: 'wrap',
    gap: 16,
  },
  footerText: {
    color: '#666',
    fontSize: 12,
  },
});
